import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

import { db } from './client';
import migrations from './migrations/migrations';

export interface DatabaseState {
  ready: boolean;
  error: Error | undefined;
}

/**
 * Run pending migrations. The root layout holds the splash until this
 * resolves, so nothing can query a schema that does not exist yet.
 *
 * Migrations are generated by `npm run db:generate` and committed — they are
 * not derived at runtime, so a build always knows exactly which schema it is
 * expecting.
 */
export function useDatabase(): DatabaseState {
  const { success, error } = useMigrations(db, migrations);
  return { ready: success, error };
}
